CREATE TABLE IF NOT EXISTS MEASUREMENTS
(
    ID          BIGSERIAL PRIMARY KEY,
    PUBLIC_ID   UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    USER_ID     BIGINT      NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    RECORDED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DETAILS     JSONB       NOT NULL,
    TYPE        VARCHAR(30) NOT NULL
);

CREATE INDEX IDX_MEAS_USER_ID ON MEASUREMENTS (USER_ID);