CREATE TABLE IF NOT EXISTS MEASUREMENT_VALUES
(
    ID             BIGSERIAL PRIMARY KEY,
    PUBLIC_ID      UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    MEASUREMENT_ID BIGINT      NOT NULL REFERENCES MEASUREMENTS (ID) ON DELETE CASCADE,
    CREATED_AT     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALUE          REAL        NOT NULL,
    ASPECT         VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX IDX_UNQ_MEAS_VAL_MEAS_ID_ASP ON MEASUREMENT_VALUES (MEASUREMENT_ID, ASPECT);