openapi: 3.1.0
info:
  title: Health tracker API
  description: Health tracker API
  version: 1.0.0
servers:
  - url: /api
    description: local
paths:
  /auth/register:
    post:
      tags:
        - auth
      operationId: register
      description: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        200:
          description: Successfully registered
        400:
          $ref: '#/components/responses/BadRequestWithErrors'
  /auth/login:
    post:
      tags:
        - auth
      operationId: login
      description: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
  /measurement:
    post:
      tags:
        - measurement
      operationId: saveMeasurement
      description: Saves measurement and its values
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementWithValuesRequest'
      responses:
        201:
          description: Successfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeasurementWithValuesResponse'
        400:
          $ref: '#/components/responses/BadRequestWithErrors'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    BadRequestWithErrors:
      description: Contains error description
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
  schemas:
    MeasurementWithValuesRequest:
      type: object
      description: Measurement record with its values creation/update request
      properties:
        id:
          type: string
          format: uuid
          description: Record id
        type:
          type: string
          description: Measurement type
          minLength: 1
          maxLength: 30
        recordedAt:
          type: string
          format: date-time
          description: Time of measurement
        details:
          type: object
          description: Measurement details (JSON)
          additionalProperties: true
        values:
          type: object
          descriptions: Measurement value map
          additionalProperties:
            type: number
            format: float
      required:
        - type
        - recordedAt
        - values
    MeasurementWithValuesResponse:
      type: object
      description: Measurement record with its values response
      properties:
        id:
          type: string
          format: uuid
          description: recordId
        type:
          type: string
          description: Measurement type
        recordedAt:
          type: string
          format: date-time
          description: Time of measurement
        createdAt:
          type: string
          format: date-time
          description: Record created at
        details:
          type: object
          description: Measurement details (JSON)
          additionalProperties: true
        values:
          type: array
          descriptions: Measurement values
          items:
            $ref: '#/components/schemas/MeasurementValueResponse'
    MeasurementValueResponse:
      type: object
      description: Distinct measurement value
      properties:
        id:
          type: string
          format: uuid
          description: Record ID
        createdAt:
          type: string
          format: date-time
          description: Record created at
        value:
          type: number
          format: float
          description: Value of a measurement
        aspect:
          type: string
          description: Aspect measured
    ApiErrorResponse:
      type: object
      description: Contains error description
      properties:
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: array
          description: Array of error details
          items:
            $ref: '#/components/schemas/ApiSubError'
      required:
        - timestamp
        - code
        - message
    ApiSubError:
      type: object
      description: Error details
      properties:
        code:
          type: string
          description: Sub error code
        message:
          type: string
          description: Message
        field:
          type: string
          description: Field producing error
        params:
          type: object
          description: Error code params
          additionalProperties: true
      required:
        - code
        - message
    LoginRequest:
      description: Login credentials
      type: object
      properties:
        username:
          type: string
          description: Username
          minLength: 4
          maxLength: 50
        password:
          type: string
          description: Password
          minLength: 8
          maxLength: 255
      required:
        - username
        - password
    RegistrationRequest:
      description: Registration request
      allOf:
        - $ref: '#/components/schemas/LoginRequest'
        - type: object
          properties:
            email:
              type: string
              description: Email address
              minLength: 1
              maxLength: 255
              format: email
            firstName:
              type: string
              description: First name
              minLength: 1
              maxLength: 100
            lastName:
              type: string
              description: Last name
              minLength: 1
              maxLength: 100
          required:
            - username
            - email
            - password
            - firstName
    JwtResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    TestResponse:
      type: object
      properties:
        message:
          type: string
          description: Test response message
security:
  - bearerAuth: [ ]
  
